# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule SwaggerPetstore.Model.Amount do
  @moduledoc """
  some description 
  """

  @derive [Poison.Encoder]
  defstruct [
    :"value",
    :"currency"
  ]

  @type t :: %__MODULE__{
    :"value" => float(),
    :"currency" => Currency
  }
end

defimpl Poison.Decoder, for: SwaggerPetstore.Model.Amount do
  import SwaggerPetstore.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"currency", :struct, SwaggerPetstore.Model.Currency, options)
  end
end

